"""Author-reviewed seed records. Standard library only; no generated biographies."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
people=[]
def source(title,url,kind='Historical scholarship',note=''):
 return dict(title=title,url=url,kind=kind,note=note,accessed='2026-09-08')
def q(ref):return source('Qur’an '+ref,'https://quran.com/'+ref.replace(':','/'),'Qur’anic account','Verse reference; story text is an original paraphrase, not a translation.')
def add(id,name,arabic,category,era,date,place,role,chapters,sources,note='',year=None,coords=None):
 people.append(dict(id=id,name=name,arabic=arabic,category=category,era=era,date=date,year=year,place=place,coordinates=coords,role=role,chapters=[dict(title=t,text=b,sources=s) for t,b,s in chapters],sources=sources,uncertainty=note,reviewed='2026-09-08'))
def prophet(id,name,ar,role,a,ra,b,rb,place='Location not established'):
 add(id,name,ar,'Prophets','Qur’anic accounts','Date not established',place,role,[('In the Qur’an',a,[0]),('The account continues',b,[1])],[q(ra),q(rb)],'The Qur’an does not give a calendar date for this life. This is a scriptural account; no independently verified date or precise geographical location is asserted.')
prophet('adam','Adam','آدم','Knowledge and repentance','The Qur’an describes Allah teaching Adam the names and the angels being commanded to bow before him. Iblis refuses.','2:30-34','After the transgression, Adam receives words from his Lord and his repentance is accepted. The account makes room for return after wrongdoing.','2:35-37')
prophet('idris','Idris','إدريس','Truthfulness and patience','Idris is described as a truthful prophet, raised to a high station.','19:56-57','He is named with Ismail and Dhul-Kifl among those who were patient. These brief passages do not supply a full biography.','21:85-86')
prophet('nuh','Nuh','نوح','A messenger to his people','Nuh calls his people to worship Allah alone. The Qur’an describes opposition from their leaders.','11:25-27','He is instructed to construct the ark. Later, the account names al-Judi as its resting place; a precise modern identification is not asserted here.','11:37-44')
prophet('hud','Hud','هود','The call to ‘Ad','Hud is sent to ‘Ad and calls them to worship Allah. He asks no payment from his people for delivering the message.','11:50-51','The Qur’an describes Hud and those who believe with him being rescued by divine mercy.','11:58','The people of ‘Ad; exact location not established')
prophet('salih','Salih','صالح','A warning to Thamud','Salih calls Thamud to worship Allah and presents the she-camel as a sign. He warns them against harming her.','7:73','The account describes the killing of the camel and the punishment that follows. Salih says he had delivered his Lord’s message and counselled his people.','7:77-79','Thamud; no precise location asserted')
prophet('ibrahim','Ibrahim','إبراهيم','Faith and the House','The Qur’an presents Ibrahim as devoted to Allah, rejecting the assignment of partners to Him.','3:67','Ibrahim and Ismail raise the foundations of the House and ask Allah to accept their work. Their prayer also concerns the generations to come.','2:127-129','The House in the Qur’anic account')
prophet('lut','Lut','لوط','Deliverance from a corrupt town','The Qur’an describes Lut as receiving judgement and knowledge, and being rescued from a town associated with wrongdoing.','21:74','He is also named among those preferred by Allah in the Qur’an’s enumeration of earlier messengers.','6:86','An unnamed town in the cited passage')
prophet('ismail','Ismail','إسماعيل','A promise kept','Ismail is described as a messenger and prophet who keeps his word and instructs his people in prayer and charity.','19:54-55','He joins Ibrahim in raising the foundations of the House, praying that their work will be accepted.','2:127','The House in the Qur’anic account')
prophet('ishaq','Ishaq','إسحاق','A family of guidance','Ishaq is named with Yaqub as a gift to Ibrahim; the passage describes them as guided.','6:84','In Surah Maryam, the account again names Ishaq and Yaqub and says each was made a prophet.','19:49')
prophet('yaqub','Yaqub','يعقوب','A prophet in Ibrahim’s family','Yaqub is named alongside Ishaq among the guided descendants in the Qur’anic account.','6:84','Surah Maryam explicitly includes Yaqub among those made prophets.','19:49')
prophet('yusuf','Yusuf','يوسف','Trust and forgiveness','Yusuf asks to be entrusted with the storehouses of the land, describing his ability to protect and manage them.','12:55','When his brothers face him, he releases them from reproach and asks that Allah forgive them.','12:92','Egypt in the Yusuf account')
prophet('ayyub','Ayyub','أيوب','A prayer in suffering','Ayyub calls upon his Lord during affliction, invoking divine mercy.','21:83','The next verse describes the removal of his suffering and the restoration of his family as a mercy and reminder.','21:84')
prophet('shuayb','Shuayb','شعيب','Faith and honest dealing','Shuayb calls the people of Madyan to worship Allah and deal fairly in weights, measures, and other people’s property.','7:85','He describes reform as his aim, within his ability, and places his trust in Allah.','11:88','Madyan; exact location not asserted')
prophet('musa','Musa','موسى','A messenger and a brother','Musa asks for his brother Harun to assist him and share in his task.','20:29-32','Surah Maryam describes Musa as a chosen messenger and prophet, called from the side of Mount Tur.','19:51-53','Mount Tur in the account; precise site not asserted')
prophet('harun','Harun','هارون','Support in a prophetic mission','Musa asks that his brother Harun be appointed to strengthen him in his task.','20:29-32','The Qur’an describes Harun’s appointment as a prophet as a gift of divine mercy to Musa.','19:53')
prophet('dhul-kifl','Dhul-Kifl','ذو الكفل','Patience in a brief account','Dhul-Kifl is named with Ismail and Idris among the patient.','21:85','The following verse includes them among the righteous admitted to divine mercy. The text does not give Dhul-Kifl a detailed life story.','21:86')
people[-1]['uncertainty']+=' Commonly included in the traditional list of 25 prophets; commentators differ over whether these verses establish his prophethood. Identification with Ezekiel is not asserted.'
prophet('dawud','Dawud','داود','Judgement and praise','The Qur’an describes Dawud and Sulayman judging a case concerning a field.','21:78','Both receive judgement and knowledge. The mountains and birds are described as praising Allah with Dawud.','21:79')
prophet('sulayman','Sulayman','سليمان','Understanding and judgement','Sulayman appears with Dawud in the account of a judgement concerning a field.','21:78','Allah grants Sulayman understanding of the case, while affirming the judgement and knowledge bestowed on both men.','21:79')
prophet('ilyas','Ilyas','إلياس','Among the righteous','Ilyas is named with Zakariyya, Yahya, and Isa among the righteous.','6:85','The passage continues by identifying the enumerated figures as recipients of scripture, authority, and prophethood.','6:89')
prophet('alyasa','Al-Yasa','اليسع','A name preserved in revelation','Al-Yasa is named alongside Ismail, Yunus, and Lut among those preferred by Allah.','6:86','The passage identifies these figures as recipients of scripture, authority, and prophethood. It does not provide Al-Yasa’s full biography.','6:89')
prophet('yunus','Yunus','يونس','A call from darkness','Yunus is named among earlier figures favoured by Allah.','6:86','The account of the man of the fish describes a prayer from darkness, acknowledging wrongdoing; the following verse describes deliverance from distress.','21:87-88')
prophet('zakariyya','Zakariyya','زكريا','A prayer answered','Zakariyya prays privately to his Lord, describing his old age and asking for an heir.','19:2-6','He receives the news of a son named Yahya. The account explicitly presents the birth as divine favour.','19:7')
prophet('yahya','Yahya','يحيى','The gift of a son','Yahya is the name given in the announcement to Zakariyya that he will have a son.','19:7','He is also named among the righteous in Surah al-An‘am’s list of earlier prophetic figures.','6:85')
prophet('isa','Isa','عيسى','A messenger to the Children of Israel','In the Qur’anic account, Isa identifies himself as a servant of Allah who has received scripture and been made a prophet.','19:30','He is sent to the Children of Israel with signs, including healing, explicitly described as occurring by Allah’s permission.','3:49','The Children of Israel; no birthplace asserted')
whe=lambda title,slug:source(title+' — World History Encyclopedia','https://www.worldhistory.org/'+slug+'/')
bukh=lambda n:source('Sahih al-Bukhari '+str(n),'https://sunnah.com/bukhari:'+str(n),'Hadith','Sahih collection in Sunni tradition; this is a transmitted report, not a contemporary eyewitness document.')
add('muhammad','Muhammad','محمد','Prophets','Early Islam','c. 570–632 CE','Mecca and Medina','The Prophet of Islam',[('The beginning of revelation','Islamic tradition describes Muhammad receiving revelation at Hira and returning to Khadijah, who reassures him. The report is transmitted by Aisha in Sahih al-Bukhari.',[0]),('A community in Medina','The migration to Medina in 622 marks a central turning point in his mission. Muhammad died in 632. The Qur’an calls him the Messenger of Allah and the seal of the prophets.',[1,2])],[bukh(3),whe('Prophet Muhammad','Prophet_Muhammad'),q('33:40')],'The birth year is approximate. Religious claims are identified as Qur’anic or hadith accounts.',570,[24.47,39.61])
add('maryam','Maryam','مريم','Qur’anic people','Qur’anic accounts','Date not established','Location not established','Devotion and the birth of Isa',[('Chosen and purified','The Qur’an describes angels announcing to Maryam that Allah has chosen and purified her.',[0]),('The announcement','Surah Maryam recounts her withdrawal from her family and the arrival of a messenger announcing a son. Her question about bearing a child is part of the account.',[1])],[q('3:42'),q('19:16-22')],'No exact date or birthplace is supplied by these passages. Maryam’s status as a prophet is debated; she is classified here as a Qur’anic person.')
add('khadijah','Khadijah bint Khuwaylid','خديجة بنت خويلد','Sahabah','Early Islam','Late 6th–early 7th century CE','Mecca','Support at the beginning',[('A return from Hira','In the report of the first revelation, Muhammad returns frightened to his wife Khadijah. She reassures him by recalling his care for relatives, guests, and people in need.',[0]),('Seeking understanding','The same report says Khadijah takes Muhammad to her cousin Waraqah ibn Nawfal to hear what happened. Her response forms a central part of the transmitted account of revelation’s beginning.',[0])],[bukh(3)],'Her exact birth year and age at marriage are not asserted. This account follows the Sunni hadith report.',None,[21.42,39.83])
add('aisha','Aisha bint Abi Bakr','عائشة بنت أبي بكر','Sahabah','Early Islam','7th century CE','Medina','A transmitter of knowledge',[('Preserving an account','Aisha is the named transmitter of the account of the beginning of revelation in Sahih al-Bukhari. Her narration preserves the story of Muhammad’s return to Khadijah.',[0]),('A source of understanding','A report from Abu Musa describes the Companions consulting Aisha when they needed help understanding a hadith. It bears witness to her place in the transmission of religious knowledge.',[1])],[bukh(3),source('Jami‘ at-Tirmidhi 3883','https://sunnah.com/tirmidhi:3883','Hadith','Graded Hasan by Darussalam on the consulted page.')],'These are reports within Sunni hadith collections. They are not a comprehensive account of her life.',None,[24.47,39.61])
for id,name,ar,dates,role,chapters,slug in [
 ('abu-bakr','Abu Bakr','أبو بكر','c. 573–634 CE','The first caliph',[('Companionship','Abu Bakr was an early Muslim and accompanied Muhammad on the migration from Mecca to Medina in 622.',[0]),('After 632','He became the first caliph after Muhammad’s death and ruled until 634. His reign included the Ridda wars and the consolidation of rule in Arabia.',[0])],'Abu_Bakr'),
 ('umar','Umar ibn al-Khattab','عمر بن الخطاب','Died 644 CE','The second caliph',[('A succession','Umar succeeded Abu Bakr in 634 and led the caliphate until 644.',[0]),('A changing state','His reign saw expansion into Byzantine and Sasanian territories and changes to the administration of the growing state.',[0])],'Umar'),
 ('uthman','Uthman ibn Affan','عثمان بن عفان','Died 656 CE','The third caliph',[('Leadership','Uthman succeeded Umar and ruled from 644 to 656. His death came during a rebellion against his government.',[0]),('The written Qur’an','Sahih al-Bukhari reports Uthman commissioning copies of the Qur’an from manuscripts held by Hafsah and sending copies to different regions.',[1])],'Uthman'),
 ('ali','Ali ibn Abi Talib','علي بن أبي طالب','Died 661 CE','Caliph and imam',[('Family and community','Ali was Muhammad’s cousin and son-in-law. He became caliph in 656.',[0]),('A divided community','His caliphate unfolded during the first civil war. He was assassinated in 661. Sunni tradition counts him as the fourth rightly guided caliph; Shia tradition recognises him as the first imam.',[0])],'Ali_ibn_Abi_Talib')]:
 add(id,name,ar,'Sahabah','Early Islam',dates,'Medina' if id!='ali' else 'Kufa',role,chapters,[whe(name,slug)]+([bukh(4987)] if id=='uthman' else []),'Succession and religious authority are interpreted differently in Sunni and Shia traditions. A short historical summary does not settle those differences.',None,[24.47,39.61] if id!='ali' else [32.03,44.4])
mac=lambda slug:source('MacTutor — University of St Andrews','https://mathshistory.st-andrews.ac.uk/Biographies/'+slug+'/')
for id,name,ar,dates,place,role,chapters,src,notes,year,coords in [
 ('al-khwarizmi','Al-Khwarizmi','الخوارزمي','c. 780–c. 850 CE','Baghdad','Practical mathematics',[('Working in Baghdad','Al-Khwarizmi worked under the patronage of the Abbasid caliph al-Ma’mun. His mathematical writing addressed practical problems as well as methods of calculation.',[0]),('Words that travelled','His algebra treatise helped give algebra its name. The word algorithm derives from the Latin form of his name; his work helped transmit Indian numeral methods.',[0])],mac('Al-Khwarizmi'),'His birthplace is uncertain and his life dates approximate. He did not invent the Indian numerals.',780,[33.31,44.37]),
 ('ibn-al-haytham','Ibn al-Haytham','ابن الهيثم','c. 965–c. 1040 CE','Basra and Cairo','Investigating light',[('A life in inquiry','Ibn al-Haytham wrote on mathematics, astronomy, and optics. His career connected Basra with Egypt.',[0]),('Light and vision','His Book of Optics examined vision, reflection, and refraction. He argued that light enters the eye from objects, and used experiments in investigating optical questions.',[0])],mac('Al-Haytham'),'Accounts of his dealings with al-Hakim differ. Stories of feigned madness are not presented here as settled facts. Death dates vary around 1039–1040.',965,[30.04,31.24]),
 ('al-biruni','Al-Biruni','البيروني','973–c. 1048 CE','Khwarazm and Ghazna','Astronomy across cultures',[('Observation and calculation','Born near Kath in Khwarazm, al-Biruni studied astronomy and mathematics. His observations helped determine geographical positions.',[0]),('Studying India','He studied Sanskrit sources and wrote about Indian religion, customs, astronomy, and learning. His work emerged amid political upheaval and Ghaznavid expansion.',[0])],mac('Al-Biruni'),'Dates of particular journeys are uncertain. This summary does not claim his travel was voluntary.',973,[33.55,68.42]),
 ('ibn-sina','Ibn Sina','ابن سينا','10th century–1037 CE','Bukhara and Iranian cities','Medicine and philosophy',[('Learning and movement','Ibn Sina grew up in the intellectual world of Bukhara. His career later took him to several courts, where he worked as a physician and adviser.',[0]),('An enduring body of work','His Canon of Medicine became influential in medical teaching, including through Latin translation. His philosophical writings shaped debate across the Islamic world. He died in Hamadan in 1037.',[0])],source('Ibn Sina — Stanford Encyclopedia of Philosophy','https://plato.stanford.edu/entries/ibn-sina/'),'The conventional birth year 980 is disputed. The consulted Stanford entry argues for an earlier date, approximately 970; no exact year is asserted.',None,[39.77,64.42]),
 ('saladin','Salah al-Din','صلاح الدين','c. 1137–1193 CE','Egypt and Syria','Ayyubid rule',[('Power and alliances','Salah al-Din, known as Saladin, built his power in Egypt and Syria through both military action and diplomacy.',[0]),('Jerusalem in 1187','His forces defeated the Crusader army at Hattin and captured Jerusalem in 1187. His career also involved wars against Muslim rivals; it cannot be reduced to later stories of chivalry.',[0])],whe('Saladin','Saladin'),'Birth dates are given as 1137 or 1138 in different references. Later heroic literature is not treated as direct evidence.',1137,[33.51,36.29]),
 ('mansa-musa','Mansa Musa','منسا موسى','Active in the early 14th century','Mali and the pilgrimage to Mecca','Pilgrimage and patronage',[('A West African ruler','Mansa Musa ruled the Mali Empire. His pilgrimage brought him through Cairo in 1324, where accounts of his wealth attracted attention.',[0]),('Learning and exchange','His patronage supported Islamic buildings and scholarship. His life belongs to a wider history of trans-Saharan trade, pilgrimage, and intellectual exchange.',[0])],whe('Mansa Musa','Mansa_Musa_I'),'The end of his reign is disputed. Modern dollar valuations and “richest person ever” rankings are not reliable historical measurements.',None,[16.77,-3.01]),
 ('ibn-battuta','Ibn Battuta','ابن بطوطة','Journeys from 1325','Tangier and Afro-Eurasia','A traveller’s account',[('Leaving home','Ibn Battuta left Tangier in 1325 to undertake the pilgrimage to Mecca. His travels continued far beyond the initial pilgrimage.',[0]),('Remembering the journey','His recollections became the Rihla, dictated after his return. It is an important account of connected Muslim societies, but a travel narrative requires critical reading rather than treating every passage as an independently confirmed visit.',[0,1])],source('The Travels of Ibn Battuta — UC Berkeley ORIAS','https://orias.berkeley.edu/resources-teachers/travels-ibn-battuta'),'Dates and routes in the Rihla are debated. The map marks Tangier, his point of departure, not every claimed destination.',None,[35.76,-5.83]),
 ('sinan','Mimar Sinan','معمار سنان','16th century CE','Edirne','Architecture and public life',[('Building for a city','Sinan designed the Selimiye Mosque complex in Edirne for Selim II. Its great dome and four minarets remain defining features of the city’s skyline.',[0]),('Beyond a prayer hall','The complex included educational and commercial spaces alongside the mosque. It illustrates the Ottoman külliye: a group of buildings serving religious and social functions together.',[0])],source('Selimiye Mosque and its Social Complex — UNESCO','https://whc.unesco.org/en/list/1366/'),'This entry focuses on a surviving, documented work rather than reconstructing uncertain details of his early life.',None,[41.68,26.56]),
 ('ahmed-zewail','Ahmed Zewail','أحمد زويل','1946–2016 CE','Pasadena, California','Seeing chemical change',[('A new timescale','Ahmed Zewail’s research made it possible to study atomic motion during chemical reactions on femtosecond timescales. This work helped establish femtochemistry.',[0]),('Science in a connected world','A Caltech professor, he received the 1999 Nobel Prize in Chemistry. His later work included four-dimensional electron microscopy. He died in 2016.',[0])],source('Ahmed Zewail, 1946–2016 — Caltech','https://www.caltech.edu/about/news/ahmed-zewail-1946-2016-51594'),'Included in the modern history of people from the Muslim world; scientific achievement is not used as evidence for a theological claim.',1946,[34.14,-118.14])]:
 add(id,name,ar,'Historical people','Modern world' if id=='ahmed-zewail' else 'Ottoman world' if id=='sinan' else 'Medieval worlds',dates,place,role,chapters,[src]+([source('Ibn Battuta — translated selections, Fordham','https://sourcebooks.web.fordham.edu/source/1354-ibnbattuta.asp','Historical primary text')] if id=='ibn-battuta' else []),notes,year,coords)
from quran_people import extend
extend(add,q)
from place_evidence import apply
apply(people,q)
(ROOT/'public/data/people.json').write_text(json.dumps({'version':1,'reviewed':'2026-09-08','coverage':'Partial collection; exhaustive corpus indexing is in progress.','people':people},ensure_ascii=False,indent=2)+'\n')
print(f'Wrote {len(people)} people, {sum(p["category"]=="Prophets" for p in people)} prophet entries')
