"""Author-reviewed seed records. Standard library only; no generated biographies."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
people=[]
SURAH_NAMES={2:'Al-Baqarah',3:'Ali ‘Imran',5:'Al-Ma’idah',6:'Al-An‘am',7:'Al-A‘raf',9:'At-Tawbah',10:'Yunus',11:'Hud',12:'Yusuf',16:'An-Nahl',18:'Al-Kahf',19:'Maryam',20:'Ta-Ha',21:'Al-Anbiya',27:'An-Naml',28:'Al-Qasas',31:'Luqman',33:'Al-Ahzab',66:'At-Tahrim',111:'Al-Masad'}
def source(title,url,kind='Historical scholarship',note=''):
 return dict(title=title,url=url,kind=kind,note=note,accessed='2026-09-08')
def q(ref):
 chapter=int(ref.split(':')[0]);name=SURAH_NAMES[chapter]
 return source(f'Qur’an — Surah {name} {ref}','https://quran.com/'+ref.replace(':','/'),'Qur’anic account','Verse reference; story text is an original paraphrase, not a translation.')
def add(id,name,arabic,category,era,date,place,role,chapters,sources,note='',year=None,coords=None):
 people.append(dict(id=id,name=name,arabic=arabic,category=category,era=era,date=date,year=year,place=place,coordinates=coords,role=role,chapters=[dict(title=t,text=b,sources=s) for t,b,s in chapters],sources=sources,uncertainty=note,reviewed='2026-09-08',editorialReview=dict(status='structure-checked',reviewedOn='2026-09-08',scholarReviewed=False,scope='Required fields, source links, evidence labels, and uncertainty presence; not theological approval or exhaustive source review.')))
def prophet(id,name,ar,role,a,ra,b,rb,place='Location not established'):
 add(id,name,ar,'Prophets','Qur’anic accounts','Date not established',place,role,[('In the Qur’an',a,[0]),('The account continues',b,[1])],[q(ra),q(rb)],'The Qur’an does not give a calendar date for this life. This is a scriptural account; no independently verified date or precise geographical location is asserted.')
prophet('adam','Adam','آدم','Knowledge and repentance','The Qur’an describes Allah teaching Adam the names and the angels being commanded to bow before him. Iblis refuses.','2:30-34','After the transgression, Adam receives words from his Lord and his repentance is accepted. The account makes room for return after wrongdoing.','2:35-37')
prophet('idris','Idris','إدريس','Truthfulness and patience','Idris is described as a truthful prophet, raised to a high station.','19:56-57','He is named with Ismail and Dhul-Kifl among those who were patient. These brief passages do not supply a full biography.','21:85-86')
prophet('nuh','Nuh','نوح','A messenger to his people','Nuh calls his people to worship Allah alone. The Qur’an describes opposition from their leaders.','11:25-27','He is instructed to construct the ark. Later, the account names al-Judi as its resting place; a precise modern identification is not asserted here.','11:37-44')
prophet('hud','Hud','هود','The call to ‘Ad','Hud is sent to ‘Ad and calls them to worship Allah. He asks no payment from his people for delivering the message.','11:50-51','The Qur’an describes Hud and those who believe with him being rescued by divine mercy.','11:58','The people of ‘Ad; exact location not established')
prophet('salih','Salih','صالح','A warning to Thamud','Salih calls Thamud to worship Allah and presents the she-camel as a sign. He warns them against harming her.','7:73','The account describes the killing of the camel and the punishment that follows. Salih says he had delivered his Lord’s message and counselled his people.','7:77-79','Thamud; no precise location asserted')
prophet('ibrahim','Ibrahim','إبراهيم','Faith and the House','The Qur’an presents Ibrahim as devoted to Allah, rejecting the assignment of partners to Him.','3:67','Ibrahim and Ismail raise the foundations of the House and ask Allah to accept their work. Their prayer also concerns the generations to come.','2:127-129','The House in the Qur’anic account')
prophet('lut','Lut','لوط','Deliverance from a corrupt town','The Qur’an describes Lut as receiving judgement and knowledge, and being rescued from a town associated with wrongdoing.','21:74','He is also named among those preferred by Allah in the Qur’an’s enumeration of earlier messengers.','6:86','An unnamed town in the cited passage')
prophet('ismail','Ismail','إسماعيل','A promise kept','Ismail is described as a messenger and prophet who keeps his word and instructs his people in prayer and charity.','19:54-55','He joins Ibrahim in raising the foundations of the House, praying that their work will be accepted.','2:127','The House in the Qur’anic account')
prophet('ishaq','Ishaq','إسحاق','A family of guidance','Ishaq is named with Yaqub as a gift to Ibrahim; the passage describes them as guided.','6:84','In Surah Maryam, the account again names Ishaq and Yaqub and says each was made a prophet.','19:49')
prophet('yaqub','Yaqub','يعقوب','A prophet in Ibrahim’s family','Yaqub is named alongside Ishaq among the guided descendants in the Qur’anic account.','6:84','Surah Maryam explicitly includes Yaqub among those made prophets.','19:49')
prophet('yusuf','Yusuf','يوسف','Trust and forgiveness','Yusuf asks to be entrusted with the storehouses of the land, describing his ability to protect and manage them.','12:55','When his brothers face him, he releases them from reproach and asks that Allah forgive them.','12:92','Egypt in the Yusuf account')
prophet('ayyub','Ayyub','أيوب','A prayer in suffering','Ayyub calls upon his Lord during affliction, invoking divine mercy.','21:83','The next verse describes the removal of his suffering and the restoration of his family as a mercy and reminder.','21:84')
prophet('shuayb','Shuayb','شعيب','Faith and honest dealing','Shuayb calls the people of Madyan to worship Allah and deal fairly in weights, measures, and other people’s property.','7:85','He describes reform as his aim, within his ability, and places his trust in Allah.','11:88','Madyan; exact location not asserted')
prophet('musa','Musa','موسى','A messenger and a brother','Musa asks for his brother Harun to assist him and share in his task.','20:29-32','Surah Maryam describes Musa as a chosen messenger and prophet, called from the side of Mount Tur.','19:51-53','Mount Tur in the account; precise site not asserted')
prophet('harun','Harun','هارون','Support in a prophetic mission','Musa asks that his brother Harun be appointed to strengthen him in his task.','20:29-32','The Qur’an describes Harun’s appointment as a prophet as a gift of divine mercy to Musa.','19:53')
prophet('dhul-kifl','Dhul-Kifl','ذو الكفل','Patience in a brief account','Dhul-Kifl is named with Ismail and Idris among the patient.','21:85','The following verse includes them among the righteous admitted to divine mercy. The text does not give Dhul-Kifl a detailed life story.','21:86')
people[-1]['uncertainty']+=' Commonly included in the traditional list of 25 prophets; commentators differ over whether these verses establish his prophethood. Identification with Ezekiel is not asserted.'
prophet('dawud','Dawud','داود','Judgement and praise','The Qur’an describes Dawud and Sulayman judging a case concerning a field.','21:78','Both receive judgement and knowledge. The mountains and birds are described as praising Allah with Dawud.','21:79')
prophet('sulayman','Sulayman','سليمان','Understanding and judgement','Sulayman appears with Dawud in the account of a judgement concerning a field.','21:78','Allah grants Sulayman understanding of the case, while affirming the judgement and knowledge bestowed on both men.','21:79')
prophet('ilyas','Ilyas','إلياس','Among the righteous','Ilyas is named with Zakariyya, Yahya, and Isa among the righteous.','6:85','The passage continues by identifying the enumerated figures as recipients of scripture, authority, and prophethood.','6:89')
prophet('alyasa','Al-Yasa','اليسع','A name preserved in revelation','Al-Yasa is named alongside Ismail, Yunus, and Lut among those preferred by Allah.','6:86','The passage identifies these figures as recipients of scripture, authority, and prophethood. It does not provide Al-Yasa’s full biography.','6:89')
prophet('yunus','Yunus','يونس','A call from darkness','Yunus is named among earlier figures favoured by Allah.','6:86','The account of the man of the fish describes a prayer from darkness, acknowledging wrongdoing; the following verse describes deliverance from distress.','21:87-88')
prophet('zakariyya','Zakariyya','زكريا','A prayer answered','Zakariyya prays privately to his Lord, describing his old age and asking for an heir.','19:2-6','He receives the news of a son named Yahya. The account explicitly presents the birth as divine favour.','19:7')
prophet('yahya','Yahya','يحيى','The gift of a son','Yahya is the name given in the announcement to Zakariyya that he will have a son.','19:7','He is also named among the righteous in Surah al-An‘am’s list of earlier prophetic figures.','6:85')
prophet('isa','Isa','عيسى','A messenger to the Children of Israel','In the Qur’anic account, Isa identifies himself as a servant of Allah who has received scripture and been made a prophet.','19:30','He is sent to the Children of Israel with signs, including healing, explicitly described as occurring by Allah’s permission.','3:49','The Children of Israel; no birthplace asserted')
whe=lambda title,slug:source(title+' — World History Encyclopedia','https://www.worldhistory.org/'+slug+'/')
bukh=lambda n:source('Sahih al-Bukhari '+str(n),'https://sunnah.com/bukhari:'+str(n),'Hadith','Sahih collection in Sunni tradition; this is a transmitted report, not a contemporary eyewitness document.')
add('muhammad','Muhammad','محمد','Prophets','Early Islam','c. 570–632 CE','Mecca and Medina','The Prophet of Islam',[('The beginning of revelation','Islamic tradition describes Muhammad receiving revelation at Hira and returning to Khadijah, who reassures him. The report is transmitted by Aisha in Sahih al-Bukhari.',[0]),('A community in Medina','The migration to Medina in 622 marks a central turning point in his mission. Muhammad died in 632. The Qur’an calls him the Messenger of Allah and the seal of the prophets.',[1,2])],[bukh(3),whe('Prophet Muhammad','Prophet_Muhammad'),q('33:40')],'The birth year is approximate. Religious claims are identified as Qur’anic or hadith accounts.',570,[24.47,39.61])
add('maryam','Maryam','مريم','Qur’anic people','Qur’anic accounts','Date not established','Location not established','Devotion and the birth of Isa',[('Chosen and purified','The Qur’an describes angels announcing to Maryam that Allah has chosen and purified her.',[0]),('The announcement','Surah Maryam recounts her withdrawal from her family and the arrival of a messenger announcing a son. Her question about bearing a child is part of the account.',[1])],[q('3:42'),q('19:16-22')],'No exact date or birthplace is supplied by these passages. Maryam’s status as a prophet is debated; she is classified here as a Qur’anic person.')
add('khadijah','Khadijah bint Khuwaylid','خديجة بنت خويلد','Sahabah','Early Islam','Late 6th–early 7th century CE','Mecca','Support at the beginning',[('A return from Hira','In the report of the first revelation, Muhammad returns frightened to his wife Khadijah. She reassures him by recalling his care for relatives, guests, and people in need.',[0]),('Seeking understanding','The same report says Khadijah takes Muhammad to her cousin Waraqah ibn Nawfal to hear what happened. Her response forms a central part of the transmitted account of revelation’s beginning.',[0])],[bukh(3)],'Her exact birth year and age at marriage are not asserted. This account follows the Sunni hadith report.',None,[21.42,39.83])
add('aisha','Aisha bint Abi Bakr','عائشة بنت أبي بكر','Sahabah','Early Islam','7th century CE','Medina','A transmitter of knowledge',[('Preserving an account','Aisha is the named transmitter of the account of the beginning of revelation in Sahih al-Bukhari. Her narration preserves the story of Muhammad’s return to Khadijah.',[0]),('A source of understanding','A report from Abu Musa describes the Companions consulting Aisha when they needed help understanding a hadith. It bears witness to her place in the transmission of religious knowledge.',[1])],[bukh(3),source('Jami‘ at-Tirmidhi 3883','https://sunnah.com/tirmidhi:3883','Hadith','Graded Hasan by Darussalam on the consulted page.')],'These are reports within Sunni hadith collections. They are not a comprehensive account of her life.',None,[24.47,39.61])
for id,name,ar,dates,role,chapters,slug in [
 ('abu-bakr','Abu Bakr','أبو بكر','c. 573–634 CE','The first caliph',[('Companionship','Abu Bakr was an early Muslim and accompanied Muhammad on the migration from Mecca to Medina in 622.',[0]),('After 632','He became the first caliph after Muhammad’s death and ruled until 634. His reign included the Ridda wars and the consolidation of rule in Arabia.',[0])],'Abu_Bakr'),
 ('umar','Umar ibn al-Khattab','عمر بن الخطاب','Died 644 CE','The second caliph',[('A succession','Umar succeeded Abu Bakr in 634 and led the caliphate until 644.',[0]),('A changing state','His reign saw expansion into Byzantine and Sasanian territories and changes to the administration of the growing state.',[0])],'Umar'),
 ('uthman','Uthman ibn Affan','عثمان بن عفان','Died 656 CE','The third caliph',[('Leadership','Uthman succeeded Umar and ruled from 644 to 656. His death came during a rebellion against his government.',[0]),('The written Qur’an','Sahih al-Bukhari reports Uthman commissioning copies of the Qur’an from manuscripts held by Hafsah and sending copies to different regions.',[1])],'Uthman'),
 ('ali','Ali ibn Abi Talib','علي بن أبي طالب','Died 661 CE','Caliph and imam',[('Family and community','Ali was Muhammad’s cousin and son-in-law. He became caliph in 656.',[0]),('A divided community','His caliphate unfolded during the first civil war. He was assassinated in 661. Sunni tradition counts him as the fourth rightly guided caliph; Shia tradition recognises him as the first imam.',[0])],'Ali_ibn_Abi_Talib')]:
 add(id,name,ar,'Sahabah','Early Islam',dates,'Medina' if id!='ali' else 'Kufa',role,chapters,[whe(name,slug)]+([bukh(4987)] if id=='uthman' else []),'Succession and religious authority are interpreted differently in Sunni and Shia traditions. A short historical summary does not settle those differences.',None,[24.47,39.61] if id!='ali' else [32.03,44.4])
mac=lambda slug:source('MacTutor — University of St Andrews','https://mathshistory.st-andrews.ac.uk/Biographies/'+slug+'/')
for id,name,ar,dates,place,role,chapters,src,notes,year,coords in [
 ('al-khwarizmi','Al-Khwarizmi','الخوارزمي','c. 780–c. 850 CE','Baghdad','Practical mathematics',[('Working in Baghdad','Al-Khwarizmi worked under the patronage of the Abbasid caliph al-Ma’mun. His mathematical writing addressed practical problems as well as methods of calculation.',[0]),('Words that travelled','His algebra treatise helped give algebra its name. The word algorithm derives from the Latin form of his name; his work helped transmit Indian numeral methods.',[0])],mac('Al-Khwarizmi'),'His birthplace is uncertain and his life dates approximate. He did not invent the Indian numerals.',780,[33.31,44.37]),
 ('ibn-al-haytham','Ibn al-Haytham','ابن الهيثم','c. 965–c. 1040 CE','Basra and Cairo','Investigating light',[('A life in inquiry','Ibn al-Haytham wrote on mathematics, astronomy, and optics. His career connected Basra with Egypt.',[0]),('Light and vision','His Book of Optics examined vision, reflection, and refraction. He argued that light enters the eye from objects, and used experiments in investigating optical questions.',[0])],mac('Al-Haytham'),'Accounts of his dealings with al-Hakim differ. Stories of feigned madness are not presented here as settled facts. Death dates vary around 1039–1040.',965,[30.04,31.24]),
 ('al-biruni','Al-Biruni','البيروني','973–c. 1048 CE','Khwarazm and Ghazna','Astronomy across cultures',[('Observation and calculation','Born near Kath in Khwarazm, al-Biruni studied astronomy and mathematics. His observations helped determine geographical positions.',[0]),('Studying India','He studied Sanskrit sources and wrote about Indian religion, customs, astronomy, and learning. His work emerged amid political upheaval and Ghaznavid expansion.',[0])],mac('Al-Biruni'),'Dates of particular journeys are uncertain. This summary does not claim his travel was voluntary.',973,[33.55,68.42]),
 ('ibn-sina','Ibn Sina','ابن سينا','10th century–1037 CE','Bukhara and Iranian cities','Medicine and philosophy',[('Learning and movement','Ibn Sina grew up in the intellectual world of Bukhara. His career later took him to several courts, where he worked as a physician and adviser.',[0]),('An enduring body of work','His Canon of Medicine became influential in medical teaching, including through Latin translation. His philosophical writings shaped debate across the Islamic world. He died in Hamadan in 1037.',[0])],source('Ibn Sina — Stanford Encyclopedia of Philosophy','https://plato.stanford.edu/entries/ibn-sina/'),'The conventional birth year 980 is disputed. The consulted Stanford entry argues for an earlier date, approximately 970; no exact year is asserted.',None,[39.77,64.42]),
 ('saladin','Salah al-Din','صلاح الدين','c. 1137–1193 CE','Egypt and Syria','Ayyubid rule',[('Power and alliances','Salah al-Din, known as Saladin, built his power in Egypt and Syria through both military action and diplomacy.',[0]),('Jerusalem in 1187','His forces defeated the Crusader army at Hattin and captured Jerusalem in 1187. His career also involved wars against Muslim rivals; it cannot be reduced to later stories of chivalry.',[0])],whe('Saladin','Saladin'),'Birth dates are given as 1137 or 1138 in different references. Later heroic literature is not treated as direct evidence.',1137,[33.51,36.29]),
 ('mansa-musa','Mansa Musa','منسا موسى','Active in the early 14th century','Mali and the pilgrimage to Mecca','Pilgrimage and patronage',[('A West African ruler','Mansa Musa ruled the Mali Empire. His pilgrimage brought him through Cairo in 1324, where accounts of his wealth attracted attention.',[0]),('Learning and exchange','His patronage supported Islamic buildings and scholarship. His life belongs to a wider history of trans-Saharan trade, pilgrimage, and intellectual exchange.',[0])],whe('Mansa Musa','Mansa_Musa_I'),'The end of his reign is disputed. Modern dollar valuations and “richest person ever” rankings are not reliable historical measurements.',None,[16.77,-3.01]),
 ('ibn-battuta','Ibn Battuta','ابن بطوطة','Journeys from 1325','Tangier and Afro-Eurasia','A traveller’s account',[('Leaving home','Ibn Battuta left Tangier in 1325 to undertake the pilgrimage to Mecca. His travels continued far beyond the initial pilgrimage.',[0]),('Remembering the journey','His recollections became the Rihla, dictated after his return. It is an important account of connected Muslim societies, but a travel narrative requires critical reading rather than treating every passage as an independently confirmed visit.',[0,1])],source('The Travels of Ibn Battuta — UC Berkeley ORIAS','https://orias.berkeley.edu/resources-teachers/travels-ibn-battuta'),'Dates and routes in the Rihla are debated. The map marks Tangier, his point of departure, not every claimed destination.',None,[35.76,-5.83]),
 ('sinan','Mimar Sinan','معمار سنان','16th century CE','Edirne','Architecture and public life',[('Building for a city','Sinan designed the Selimiye Mosque complex in Edirne for Selim II. Its great dome and four minarets remain defining features of the city’s skyline.',[0]),('Beyond a prayer hall','The complex included educational and commercial spaces alongside the mosque. It illustrates the Ottoman külliye: a group of buildings serving religious and social functions together.',[0])],source('Selimiye Mosque and its Social Complex — UNESCO','https://whc.unesco.org/en/list/1366/'),'This entry focuses on a surviving, documented work rather than reconstructing uncertain details of his early life.',None,[41.68,26.56]),
 ('ahmed-zewail','Ahmed Zewail','أحمد زويل','1946–2016 CE','Pasadena, California','Seeing chemical change',[('A new timescale','Ahmed Zewail’s research made it possible to study atomic motion during chemical reactions on femtosecond timescales. This work helped establish femtochemistry.',[0]),('Science in a connected world','A Caltech professor, he received the 1999 Nobel Prize in Chemistry. His later work included four-dimensional electron microscopy. He died in 2016.',[0])],source('Ahmed Zewail, 1946–2016 — Caltech','https://www.caltech.edu/about/news/ahmed-zewail-1946-2016-51594'),'Included in the modern history of people from the Muslim world; scientific achievement is not used as evidence for a theological claim.',1946,[34.14,-118.14])]:
 add(id,name,ar,'Historical people','Modern world' if id=='ahmed-zewail' else 'Ottoman world' if id=='sinan' else 'Medieval worlds',dates,place,role,chapters,[src]+([source('Ibn Battuta — translated selections, Fordham','https://sourcebooks.web.fordham.edu/source/1354-ibnbattuta.asp','Historical primary text')] if id=='ibn-battuta' else []),notes,year,coords)

# A deliberately bounded first scholar collection. Biographical evidence and the
# scriptural foundations of seeking knowledge are kept as separate source types.
q_knowledge=q('16:43')
hadith_understanding=source('Sahih al-Bukhari 71','https://sunnah.com/bukhari:71','Hadith','Sahih collection in Sunni tradition; cited for the virtue of understanding religion, not as biographical evidence.')
for id,name,ar,dates,place,role,chapters,bio,notes,year,coords in [
 ('abu-hanifa','Abu Hanifa','أبو حنيفة','c. 699–767 CE','Kufa and Baghdad','Jurisprudence and legal reasoning',[('A jurist in Kufa','Abu Hanifa, also known as al-Nu‘man ibn Thabit, became one of the most influential early Muslim jurists. The Hanafi school bears his name, though its later form also reflects the work of his students.',[0]),('A legacy developed by students','His legal thought was transmitted and systematised especially through students including Abu Yusuf and Muhammad al-Shaybani. Reports about his ancestry and some details of his life conflict.',[0])],source('Abu Hanifa — Encyclopaedia Iranica','https://www.iranicaonline.org/articles/abu-hanifa-noman-b/'), 'The exact birth date, ancestry, and attribution of some works remain disputed. This entry describes his historical influence without declaring one legal school superior.',699,[32.0,44.33]),
 ('malik-ibn-anas','Malik ibn Anas','مالك بن أنس','c. 711–795 CE','Medina','Hadith and the practice of Medina',[('Teaching in Medina','Malik ibn Anas spent his scholarly life in Medina and became a leading authority in law and hadith. The Maliki school takes its name from him.',[0]),('The Muwatta','Al-Muwatta brings together transmitted reports, legal opinions, and the practice associated with Medina. Its recensions and role in later Maliki law require more detail than a short profile can provide.',[0])],source('Malik ibn Anas — Encyclopaedia Britannica','https://www.britannica.com/biography/Malik-ibn-Anas'), 'Sources give different birth years. The relationship between Malik’s own teaching and the later Maliki school should not be collapsed into a single fixed method.',711,[24.47,39.61]),
 ('al-shafii','Al-Shafi‘i','الشافعي','767–820 CE','Mecca, Baghdad, and Cairo','Hadith, law, and legal theory',[('A travelling scholar','Muhammad ibn Idris al-Shafi‘i studied in several centres of learning, including Medina, Baghdad, and Egypt. The Shafi‘i school is named for him.',[0]),('Arguments about legal proof','His writings, especially al-Risala in its surviving form, are central to the history of Islamic legal theory and to debates about the authority of Qur’an, Sunnah, consensus, and analogy.',[0])],source('Al-Shafi‘i — Encyclopaedia Britannica','https://www.britannica.com/biography/al-Shafii'), 'Accounts of his education and the development of his legal thought come through later biographical traditions. “Founder of legal theory” is an oversimplification, so it is not claimed here.',767,[30.04,31.24]),
 ('ahmad-ibn-hanbal','Ahmad ibn Hanbal','أحمد بن حنبل','780–855 CE','Baghdad','Hadith, law, and theological witness',[('Collecting transmitted reports','Ahmad ibn Hanbal travelled in pursuit of hadith and compiled the Musnad, a large collection organised primarily by transmitting Companion.',[0]),('The mihna','During the Abbasid inquisition known as the mihna, he refused to affirm the imposed doctrine that the Qur’an was created and was imprisoned and flogged. The Hanbali legal school later took his name.',[0])],source('Ahmad ibn Hanbal — Encyclopaedia Britannica','https://www.britannica.com/biography/Ahmad-ibn-Hanbal'), 'Later traditions shaped accounts of his life and authority. This concise entry does not adjudicate later theological or legal disputes.',780,[33.31,44.37])
]:
 add(id,name,ar,'Islamic scholars','Early Islamic scholarship',dates,place,role,
  chapters+[('Qur’an and Sunnah as a shared foundation','The Qur’an directs people who do not know to ask those who possess knowledge. A report in Sahih al-Bukhari says that when Allah intends good for someone, He grants understanding of religion. These references explain the collection’s theme; they are not evidence for the individual biography.',[1,2])],
  [bio,q_knowledge,hadith_understanding],notes,year,coords)
from quran_people import extend
extend(add,q)

# Additional Qur'anic people. Later identifications are not promoted into the
# Qur'an's own wording: unnamed figures remain unnamed in their titles.
add('dhul-qarnayn','Dhul-Qarnayn','ذو القرنين','Qur’anic people','Qur’anic accounts','Date not established','Locations not established','A ruler tested with power',[('A means to travel','The Qur’an says Dhul-Qarnayn was established in the land and given means to pursue a course. The account then describes journeys without supplying a calendar date.',[0]),('A barrier by consent','Between two barriers, a people ask for protection from Gog and Magog. Dhul-Qarnayn refuses tribute, asks for their labour, and constructs a barrier while attributing its success to divine mercy.',[1])],[q('18:83-86'),q('18:92-98')],'The Qur’an does not identify Dhul-Qarnayn with Alexander, Cyrus, or another historical ruler. The locations and chronology are not asserted here.')
add('mother-musa','The mother of Musa','أم موسى','Qur’anic people','Qur’anic accounts','Date not established','Egypt in the Qur’anic account','Trust under danger',[('An instruction and a promise','The Qur’an describes inspiration to Musa’s mother: nurse him, and when she fears for him, place him in the river without fear or grief; he will be returned and made a messenger.',[0]),('Returned to his mother','Musa’s sister watches from a distance. After he refuses other nurses, his family is indicated, and he is returned to his mother so that she may be comforted.',[1])],[q('28:7'),q('28:8-13')],'Her personal name, age, and exact location are not given in these verses. “Inspiration” here follows the Qur’anic wording and is not a claim that she was a prophet.')
add('madyan-elder','The elder of Madyan','شيخ مدين','Qur’anic people','Qur’anic accounts','Date not established','Madyan','Shelter and an agreement',[('A report from two women','After Musa helps two women water their flock, one returns and says her father invites him so he may be rewarded. Musa tells the elder his story and is reassured.',[0]),('An agreed term','The elder offers Musa marriage to one of his daughters in return for eight years of service, with ten left as Musa’s choice. Musa accepts the agreement.',[1])],[q('28:23-25'),q('28:26-28')],'The Qur’an does not name this man or identify him as the prophet Shuayb. That common later identification is therefore not stated as Qur’anic fact.')
for child_id,child_name,child_arabic,focus in [
 ('adam-son-offering','One son of Adam: the accepted offering','أحد ابني آدم','whose offering was accepted'),
 ('adam-son-aggressor','One son of Adam: the aggressor','أحد ابني آدم','who threatened and killed his brother')]:
 add(child_id,child_name,child_arabic,'Qur’anic people','Qur’anic accounts','Date not established','Location not established',f'One of Adam’s two sons, {focus}',[('Two offerings','The Qur’an asks that the account of Adam’s two sons be recited truthfully: each offers a sacrifice, and one is accepted while the other is not.',[0]),('Moral responsibility','The brothers’ exchange rejects aggression; the account then describes one soul prompting the killing of the other and the killer becoming one of the losers.',[1])],[q('5:27'),q('5:28-31')],'The Qur’an does not give either son a personal name. The names Habil and Qabil belong to later interpretive tradition and are not used here as if they appeared in the verse.')

# Companion profiles rely on explicitly linked reports. Dates are kept broad
# where the consulted reports do not establish a complete modern biography.
for id,name,ar,role,chapters,reports,note in [
 ('bilal','Bilal ibn Rabah','بلال بن رباح','Caller to prayer and Companion',[('A practice remembered','In a report narrated by Abu Hurayrah, Muhammad asks Bilal about the deed in Islam from which he most hopes for reward. Bilal describes praying after purification.',[0]),('A transmitted virtue','The report connects Bilal with footsteps heard in Paradise. It is presented as a Sunni hadith report, not an independently dated biographical event.',[0])],[bukh(1149)],'This concise profile does not assert disputed details about Bilal’s birth year, later residence, or death date.'),
 ('fatimah','Fatimah bint Muhammad','فاطمة بنت محمد','Daughter of Muhammad',[('A daughter remembered','Sahih al-Bukhari preserves Muhammad’s statement that Fatimah is part of him and that what angers her angers him.',[0]),('Work and remembrance','Another report describes Fatimah’s work at the hand mill and the remembrance taught to her and Ali before sleep.',[1])],[bukh(3767),bukh(3705)],'Reports about her age, birth year, and the political disputes after Muhammad’s death require wider Sunni and Shia source review; no exact birth year is asserted.'),
 ('anas-ibn-malik','Anas ibn Malik','أنس بن مالك','Companion and transmitter',[('Ten years of service','Anas reports that his mother and aunts urged him to serve Muhammad and that he did so for ten years in Medina.',[0]),('A long transmitting life','His many narrations preserve observations of community life. This profile distinguishes what Anas says in a report from later reconstruction of his biography.',[1])],[bukh(5166),bukh(6038)],'Reports differ on his exact death year and age. The account is bounded to statements in the linked Sunni hadith collection.'),
 ('abu-hurayrah','Abu Hurayrah','أبو هريرة','Companion and hadith transmitter',[('Staying close to learn','Abu Hurayrah explains that he remained with Muhammad while others were occupied with markets or agriculture, attending and memorising what they missed.',[0]),('Writing and memory','He says Abdullah ibn Amr transmitted more in writing, while he himself did not write in the same way. The report is evidence about his own account of transmission.',[1])],[bukh(118),bukh(113)],'His birth name and exact dates are disputed in biographical literature. “Abu Hurayrah” is the well-known kunya used by the reports.'),
 ('asma-bint-abi-bakr','Asma bint Abi Bakr','أسماء بنت أبي بكر','Companion and migrant',[('Preparing provisions','Asma reports preparing provisions for Muhammad and Abu Bakr at the time of migration and dividing her waistband to tie their containers.',[0]),('A name from the report','The same report explains the title associated with the two waistbands. This profile does not build a full life from that single episode.',[0])],[bukh(3907)],'Her exact birth date is not established here; later biographical detail requires a broader source review.'),
 ('hafsah-bint-umar','Hafsah bint Umar','حفصة بنت عمر','Companion and custodian of manuscripts',[('Marriage in Medina','Umar’s report describes Hafsah after the death of her husband Khunays and her subsequent marriage to Muhammad.',[0]),('Manuscripts consulted','Sahih al-Bukhari reports that Qur’anic manuscripts held by Hafsah were borrowed when Uthman commissioned standard copies and then returned to her.',[1])],[bukh(4005),bukh(4987)],'The exact chronology of her birth and all manuscript-history questions are outside this short profile.'),
 ('umm-salamah','Umm Salamah','أم سلمة','Companion and transmitter',[('A named transmitter','Umm Salamah transmits reports concerning worship, family life, and events in the early Muslim community.',[0]),('Identity in the sources','The narrator catalogue identifies her as Hind bint Abi Umayyah and a wife of Muhammad; this profile retains her well-known kunya.',[0])],[source('Umm Salamah — narrator record','https://sunnah.com/narrator/8101','Hadith biographical index')],'Reports differ on her death year. This is an introductory account, not an exhaustive hadith or biographical index.'),
 ('umm-sulaym','Umm Sulaym','أم سليم','Companion and mother of Anas',[('A request for Anas','Anas narrates that Umm Sulaym asked Muhammad to pray for her son. The report explicitly identifies Anas as his servant.',[0]),('A household in the reports','Her life appears through reports transmitted by and about her family; those reports do not supply a single complete chronological biography.',[0])],[bukh(1982)],'Her personal-name variants and the chronology of her marriages require broader biographical-source comparison.'),
 ('ibn-abbas','Abdullah ibn Abbas','عبد الله بن عباس','Companion and interpreter',[('A prayer for understanding','Ibn Abbas reports that Muhammad embraced him and prayed that he be taught the Book.',[0]),('A transmitting Companion','His narrations became important to later Qur’anic interpretation and hadith transmission; this profile does not attribute every later tafsir report to him.',[0])],[bukh(75)],'The reliability and chains of individual reports attributed to Ibn Abbas must be assessed separately.'),
 ('abu-talha','Abu Talha al-Ansari','أبو طلحة الأنصاري','Companion of Medina',[('A garden given in charity','After the verse about attaining righteousness through giving what one loves, Abu Talha offers his garden Bayruha in charity.',[0]),('Direction for the gift','The report says Muhammad commends the gift and advises that it be distributed among Abu Talha’s relatives.',[0])],[bukh(1461)],'His personal name and dates appear with variants in later biographical sources; this account stays with the linked report.')]:
 add(id,name,ar,'Sahabah','Early Islam','7th century CE','Medina',role,chapters,reports,note,None,[24.47,39.61])

for id,name,ar,dates,place,role,chapters,bio,note,year,coords in [
 ('al-ghazali','Al-Ghazali','الغزالي','c. 1055/1058–1111 CE','Tus, Nishapur, Baghdad, and Damascus','Law, theology, ethics, and spiritual practice',[('Teaching and departure','Al-Ghazali taught at the Nizamiyya in Baghdad before leaving public teaching during a personal and spiritual crisis.',[0]),('A wide intellectual legacy','His works address law, theology, philosophy, ethics, and spiritual discipline. The Ihya became especially influential, while his critique of philosophers generated long debate.',[0])],source('Al-Ghazali — Encyclopaedia Britannica','https://www.britannica.com/biography/al-Ghazali'),'Sources give 1058 and earlier alternatives around 1055–56 for his birth. Accounts of his crisis depend partly on his own retrospective writing.',1058,[35.24,59.22]),
 ('ibn-rushd','Ibn Rushd (Averroes)','ابن رشد','1126–1198 CE','Cordoba and Marrakesh','Judge, physician, and philosopher',[('A judge and physician','Ibn Rushd was born in Cordoba into a family known for law. He served as a judge and later as chief physician in an Almohad court.',[0]),('Commentary and religious inquiry','He wrote on law, medicine, philosophy, and theology and produced influential commentaries on Aristotle. His relationship with Almohad authority changed late in his life.',[0])],source('Ibn Rushd — Stanford Encyclopedia of Philosophy','https://plato.stanford.edu/entries/ibn-rushd/'),'Many details of his education and the reason for his late disgrace remain unclear in the surviving sources. “Averroes” is the Latinised name by which he is often searched.',1126,[37.89,-4.78]),
 ('ibn-khaldun','Ibn Khaldun','ابن خلدون','1332–1406 CE','Tunis, North Africa, and Cairo','Historian and social theorist',[('Politics and scholarship','Born in Tunis, Ibn Khaldun served several North African courts before periods of withdrawal, travel, and teaching.',[0]),('The Muqaddimah','The introduction to his universal history examines social solidarity, political authority, economic life, and the rise and decline of dynasties. Later labels such as “founder of sociology” can obscure its medieval intellectual setting.',[0])],source('Ibn Khaldun — Encyclopaedia Britannica','https://www.britannica.com/biography/Ibn-Khaldun'),'His autobiography is a major source for his life but remains a self-authored account. Modern disciplinary titles are not treated as exact descriptions of his project.',1332,[36.81,10.18])]:
 add(id,name,ar,'Islamic scholars','Medieval worlds',dates,place,role,chapters+[('Qur’an and Sunnah as a shared foundation','The collection distinguishes these scholars’ historical arguments from the Qur’an and transmitted Sunnah that they interpreted. The thematic references do not certify every later opinion.',[1,2])],[bio,q_knowledge,hadith_understanding],note,year,coords)

from place_evidence import apply
apply(people,q)

# Sunnah coverage is explicit for every prophet. A missing specific report is
# recorded as a research gap rather than silently filled with a weak narration.
sunnah_by_prophet={
 'adam':(3326,'Sahih al-Bukhari reports the creation of Adam and the greeting of peace.'),
 'idris':(3207,'The Night Journey report names Idris among the prophets Muhammad meets.'),
 'nuh':(3340,'The intercession report names Nuh and describes his mission to his people.'),
 'salih':(3378,'Sahih al-Bukhari preserves instructions connected with the dwellings of Thamud.'),
 'ibrahim':(3358,'Sahih al-Bukhari transmits a report about Ibrahim; it is presented as a report, not independent chronology.'),
 'lut':(3372,'Sahih al-Bukhari includes a report concerning Lut.'),
 'ismail':(3364,'Sahih al-Bukhari transmits an account involving Ibrahim, Ismail, and the sanctuary.'),
 'yusuf':(3207,'The Night Journey report names Yusuf among the prophets Muhammad meets.'),
 'ayyub':(3391,'Sahih al-Bukhari transmits a report about Ayyub receiving divine blessing.'),
 'musa':(3207,'The Night Journey report names Musa and includes his advice concerning the daily prayers.'),
 'harun':(3207,'The Night Journey report names Harun among the prophets Muhammad meets.'),
 'dawud':(1131,'Sahih al-Bukhari describes the prayer and fasting associated with Dawud.'),
 'sulayman':(3424,'Sahih al-Bukhari transmits a report about Sulayman and the importance of saying “if Allah wills.”'),
 'yunus':(3416,'Sahih al-Bukhari warns against claiming superiority over Yunus ibn Matta.'),
 'yahya':(3207,'The Night Journey report names Yahya among the prophets Muhammad meets.'),
 'isa':(3207,'The Night Journey report names Isa among the prophets Muhammad meets.'),
}
key_passages={
 'adam':['2:30-39','7:11-27','20:115-123'],
 'idris':['19:56-57','21:85-86'],
 'nuh':['7:59-64','11:25-49','23:23-30','26:105-122','71:1-28'],
 'hud':['7:65-72','11:50-60','26:123-140','46:21-26'],
 'salih':['7:73-79','11:61-68','26:141-159','27:45-53','91:11-15'],
 'ibrahim':['2:124-141','6:74-83','14:35-41','19:41-50','21:51-73','26:69-89','37:83-113','60:4-6'],
 'lut':['7:80-84','11:77-83','15:57-77','26:160-175','27:54-58','29:28-35'],
 'ismail':['2:125-129','19:54-55','38:48'],
 'ishaq':['6:84','11:69-73','15:51-60','19:49-50','37:112-113'],
 'yaqub':['2:132-133','6:84','12:4-101','19:49-50'],
 'yusuf':['6:84','12:4-101','40:34'],
 'ayyub':['4:163','6:84','21:83-84','38:41-44'],
 'shuayb':['7:85-93','11:84-95','26:176-191','29:36-37'],
 'musa':['2:49-61','7:103-160','10:75-93','18:60-82','20:9-98','26:10-68','28:3-46'],
 'harun':['7:142-151','19:53','20:29-36','20:83-94'],
 'dhul-kifl':['21:85-86','38:48'],
 'dawud':['2:251','4:163','17:55','21:78-80','34:10-11','38:17-26'],
 'sulayman':['2:102','21:78-82','27:15-44','34:12-14','38:30-40'],
 'ilyas':['6:85','37:123-132'],
 'alyasa':['6:86','38:48'],
 'yunus':['4:163','6:86','10:98','21:87-88','37:139-148','68:48-50'],
 'zakariyya':['3:37-41','6:85','19:2-15','21:89-90'],
 'yahya':['3:39','6:85','19:7-15'],
 'isa':['2:87','2:253','3:45-59','4:157-171','5:110-120','19:16-36','43:57-65','61:6','61:14'],
 'muhammad':['3:144','33:40','47:2','48:29','53:1-18','96:1-5'],
}
for p in people:
 if p['category']!='Prophets': continue
 p['quranReferences']=[i for i,s in enumerate(p['sources']) if s['kind']=='Qur’anic account']
 p['keyQuranPassages']=key_passages[p['id']]
 p['factCheck']={'status':'Source-alignment checked','checked':'2026-09-08','scope':'Profile wording checked against its cited Qur’an and verified Sahih al-Bukhari references. This is not a claim of exhaustive tafsir or hadith coverage and is not a substitute for qualified scholarly review.'}
 if p['id']=='muhammad':
  p['sunnahEvidence']={'status':'Referenced','text':'The profile includes the Sahih al-Bukhari report of the beginning of revelation.','sources':[0]}
 elif p['id'] in sunnah_by_prophet:
  number,text=sunnah_by_prophet[p['id']]
  p['sources'].append(bukh(number))
  p['sunnahEvidence']={'status':'Referenced','text':text,'sources':[len(p['sources'])-1]}
 else:
  p['sunnahEvidence']={'status':'Research gap','text':'No prophet-specific report from the project’s currently verified Sahih al-Bukhari set is attached yet. This does not mean that no report exists; weaker or unverified material is not substituted.','sources':[]}
(ROOT/'public/data/people.json').write_text(json.dumps({'version':1,'reviewed':'2026-09-08','coverage':'Partial collection; exhaustive corpus indexing is in progress.','people':people},ensure_ascii=False,indent=2)+'\n')
print(f'Wrote {len(people)} people, {sum(p["category"]=="Prophets" for p in people)} prophet entries')
