def extend(add,q):
 records=[
 ('zayd','Zayd ibn Harithah','زيد بن حارثة','A named Companion','The Qur’an explicitly names Zayd in the passage concerning the end of his marriage and the Prophet’s subsequent marriage.','33:37','The verse itself names Zayd; the full identification is supplied by the tafsir shown with the verse. The Qur’an does not name his former wife in this passage.'),
 ('abu-lahab','Abu Lahab','أبو لهب','Wealth and accountability','Surah al-Masad names Abu Lahab and declares that his wealth and gains will not benefit him. The chapter also refers to his wife.','111:1-5','This is the Qur’anic account. The chapter does not supply his full genealogy or life dates.'),
 ('imran','Imran','عمران','A family remembered','The Qur’an identifies the woman making a vow concerning her unborn child as the wife of Imran.','3:35','This passage gives no detailed biography of Imran. He is not identified here with other historical people who share the name.'),
 ('wife-imran','The wife of Imran','امرأة عمران','A mother’s dedication','The wife of Imran dedicates what is in her womb to divine service and asks Allah to accept her offering.','3:35','Her personal name is not stated in this verse. Later names should be attributed to their own sources, not presented as Qur’anic wording.'),
 ('azar','Azar','آزر','In Ibrahim’s address','Ibrahim addresses Azar in a passage challenging the taking of idols as gods. The Arabic text uses the kinship term ab.','6:74','Translations commonly render the relationship as father. Some exegetical traditions interpret the relationship differently; this entry does not settle that debate.'),
 ('luqman','Luqman','لقمان','Wisdom and counsel','The Qur’an describes Luqman as receiving wisdom and being told to show gratitude to Allah. His counsel to his son warns against associating partners with Allah.','31:12-13','His name is explicit, but these verses do not give a birth date, ethnicity, or profession. Those details are not invented.'),
 ('uzayr','Uzayr','عزير','A name in a theological passage','Uzayr is named in a Qur’anic passage rejecting claims of divine sonship.','9:30','The verse is a theological statement, not a full biography or a description of what all Jewish people in every period believe. His prophetic status is not asserted here.'),
 ('talut','Talut','طالوت','A king appointed','An unnamed prophet tells his people that Allah has appointed Talut as king. Objections about wealth are answered with reference to his knowledge and stature.','2:247','Talut is commonly rendered Saul in translation. No precise date is supplied by the verse.'),
 ('jalut','Jalut','جالوت','An opponent in battle','The Qur’an recounts the defeat of an opposing force and states that Dawud killed Jalut. It then describes Dawud receiving kingship and wisdom.','2:251','Commonly rendered Goliath in translation. Later descriptions of his appearance are not added to this entry.'),
 ('qarun','Qarun','قارون','The test of wealth','Qarun is described as belonging to Musa’s people and acting arrogantly toward them. The passage describes his enormous stores of wealth and the counsel given to him.','28:76','The Qur’anic account is not assigned a historical financial valuation or an independently verified date.'),
 ('haman','Haman','هامان','In Pharaoh’s court','Pharaoh addresses Haman and orders construction of a high structure while making a claim about the God of Musa.','28:38','The Haman of this account is not automatically identified with a similarly named person in another text.'),
 ('pharaoh','Pharaoh in Musa’s account','فرعون','Power challenged','The Qur’an presents Pharaoh making a claim of exclusive divinity to his chiefs and directing Haman to build a high structure.','28:38','Pharaoh is a title. Identification with a particular Egyptian ruler is not established by this verse.'),
 ('samiri','Al-Samiri','السامري','A community misled','In Surah Taha, Musa is told that his people have been tested in his absence and that al-Samiri has led them astray.','20:85','This designation does not establish his full personal name or a modern ethnic identity.'),
 ('queen-sheba','The Queen of Sheba','ملكة سبأ','A woman who ruled','In the account of Sulayman, the hoopoe reports finding a woman ruling over a people, supplied with many things and possessing a great throne.','27:23','The Qur’an does not give her personal name. Bilqis belongs to later tradition; it is not substituted for the Qur’an’s unnamed identification.'),
 ('wife-pharaoh','The wife of Pharaoh','امرأة فرعون','Faith under power','The Qur’an presents Pharaoh’s wife as an example for believers. She asks Allah for a home near Him in Paradise and for rescue from Pharaoh and wrongdoing.','66:11','Her personal name is not stated in the verse. Asiyah is a name found in hadith and later tradition and requires separate attribution.'),
 ('sister-musa','The sister of Musa','أخت موسى','Watching from a distance','Musa’s mother tells his sister to follow him. The account describes her watching him from a distance without the others noticing.','28:11','The Qur’an does not state her personal name. This entry does not import a name from another tradition.'),
 ('wife-nuh','The wife of Nuh','امرأة نوح','Responsibility beyond family ties','The Qur’an names the wife of Nuh by her relationship in an example of disbelief. Her relationship to a righteous servant does not protect her from judgement.','66:10','The verse does not give her personal name. Its language of betrayal is not expanded into an invented allegation of sexual infidelity.'),
 ('wife-lut','The wife of Lut','امرأة لوط','Responsibility beyond family ties','The wife of Lut appears with the wife of Nuh in the Qur’an’s example of people whose family relationships did not protect them from judgement.','66:10','The verse does not give her personal name. Her entry remains distinct from the wife of Nuh.')
 ]
 for id,name,ar,role,text,ref,note in records:
  add(id,name,ar,'Sahabah' if id=='zayd' else 'Qur’anic people','Early Islam' if id in ['zayd','abu-lahab'] else 'Qur’anic accounts','7th century CE' if id in ['zayd','abu-lahab'] else 'Date not established','Location not established',role,[('In the source',text,[0])],[q(ref)],note)
